/*
 * @file ipc_server_zynq.c
 *
 * @brief Client for the inter-processor communication (IPC) library.
 */

//=============================================================================
/*-------------------------------- Includes ---------------------------------*/
//=============================================================================
#include "ipc_server_zynq.h"

/* Device and drivers */
#include "xparameters.h"
#include "xil_types.h"

#include "xil_exception.h"
#include "xscugic_hw.h"
#include "xil_printf.h"
#include "xstatus.h"
#include "xscugic.h"

#include "zynq_config.h"

#include "ipc/ipcServer.h"
//=============================================================================

//=============================================================================
/*-------------------------------- Prototypes -------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_server_zynq_irq(void *callback_ref);
//-----------------------------------------------------------------------------
//=============================================================================

//=============================================================================
/*------------------------------- Definitions -------------------------------*/
//=============================================================================
/*
 * Software generated interrupt (SIG) from CPU0 to CPU1. This interrupt is
 * generated by CPU0 to notify CPU1 that a new command is to be executed.
 */
#define IPC_SERVER_ZYNQ_INT_CPU0_TO_CPU1    ZYNQ_CONFIG_SIG_CPU0_TO_CPU1

/*
 * Software generated interrupt (SIG) from CPU1 to CPU0. This interrupt is
 * generated by CPU1 to notify CPU0 that a requested command was executed.
 */
#define IPC_SERVER_ZYNQ_INT_CPU1_TO_CPU0    ZYNQ_CONFIG_SIG_CPU1_TO_CPU0


/**/
#define IPC_SERVER_ZYNQ_CONFIG_SIG_CPU0_ID  ZYNQ_CONFIG_SIG_CPU0_ID


typedef struct{
    /* Interrupt controller instance */
    XScuGic *intc_instance;
}ipc_control_t;
//=============================================================================

//=============================================================================
/*--------------------------------- Globals ---------------------------------*/
//=============================================================================
static ipc_control_t ipc;
//=============================================================================

//=============================================================================
/*-------------------------------- Functions --------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_server_zynq_init(void *irq_inst){

    ipc.intc_instance = (XScuGic *)irq_inst;

    XScuGic_Connect(
        ipc.intc_instance,
        IPC_SERVER_ZYNQ_INT_CPU0_TO_CPU1,
        (Xil_ExceptionHandler)ipc_server_zynq_irq,
        (void  *)ipc.intc_instance
    );
    XScuGic_Enable(ipc.intc_instance, IPC_SERVER_ZYNQ_INT_CPU0_TO_CPU1);
}
//-----------------------------------------------------------------------------
int32_t ipcs_server_zynq_irq_send(void){

    XScuGic_SoftwareIntr(
        ipc.intc_instance ,
        IPC_SERVER_ZYNQ_INT_CPU1_TO_CPU0,
        IPC_SERVER_ZYNQ_CONFIG_SIG_CPU0_ID
    );

    return 0;
}
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
//=============================================================================

//=============================================================================
/*----------------------------------- IRQ -----------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_server_zynq_irq(void *callback_ref){

    (void)callback_ref;
    ipcServerRequest();
}
//-----------------------------------------------------------------------------
//=============================================================================

