/*
 * @file ipc_client_zynq.c
 *
 * @brief Client for the inter-processor communication (IPC) library.
 */

//=============================================================================
/*-------------------------------- Includes ---------------------------------*/
//=============================================================================
#include "ipc_client_zynq.h"

/* Kernel */
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"

/* Device and drivers */
#include "xparameters.h"
#include "xil_types.h"

#include "xil_exception.h"
#include "xscugic_hw.h"
#include "xil_printf.h"
#include "xstatus.h"
#include "xscugic.h"

#include "zynq_config.h"
//=============================================================================

//=============================================================================
/*-------------------------------- Prototypes -------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_client_zynq_irq(void *callback_ref);
//-----------------------------------------------------------------------------
//=============================================================================

//=============================================================================
/*------------------------------- Definitions -------------------------------*/
//=============================================================================
/*
 * Software generated interrupt (SIG) from CPU0 to CPU1. This interrupt is
 * generated by CPU0 to notify CPU1 that a new command is to be executed.
 */
#define IPC_CLIENT_ZYNQ_INT_CPU0_TO_CPU1        ZYNQ_CONFIG_SIG_CPU0_TO_CPU1

/*
 * Software generated interrupt (SIG) from CPU1 to CPU0. This interrupt is
 * generated by CPU1 to notify CPU0 that a requested command was executed.
 */
#define IPC_CLIENT_ZYNQ_INT_CPU1_TO_CPU0        ZYNQ_CONFIG_SIG_CPU1_TO_CPU0

/**/
#define IPC_CLIENT_ZYNQ_CONFIG_SIG_CPU1_ID      ZYNQ_CONFIG_SIG_CPU1_ID


typedef struct{

    /* Interrupt controller instance */
    XScuGic *intc_instance;

    /*
     * Semaphore used to signal a response from CPU1.
     *
     * This semaphore is taken before a command is issued to CPU1. When CPU1
     * replies back, an interrupt is generated in CPU0, which releases the
     * semaphore. Thus, the semaphore is used to indicate that CPU1 replied
     * to a command issued by CPU0.
     */
    SemaphoreHandle_t cpu1_semaphore;

    /*
     * Semaphore used to lock/unlock the client.
     *
     * A request is only sent to the server if the semaphore is free. The
     * semaphore is freed after receiving the server's response.
     */
    SemaphoreHandle_t lock;

}ipc_control_t;
//=============================================================================

//=============================================================================
/*--------------------------------- Globals ---------------------------------*/
//=============================================================================
static ipc_control_t ipc;
//=============================================================================

//=============================================================================
/*-------------------------------- Functions --------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_client_zynq_init(void *irq_inst){

    ipc.intc_instance = (XScuGic *)irq_inst;

    XScuGic_Connect(
        ipc.intc_instance,
        IPC_CLIENT_ZYNQ_INT_CPU1_TO_CPU0,
        (Xil_ExceptionHandler)ipc_client_zynq_irq,
        (void  *)ipc.intc_instance
    );
    XScuGic_Enable(ipc.intc_instance, IPC_CLIENT_ZYNQ_INT_CPU1_TO_CPU0);

    ipc.cpu1_semaphore = xSemaphoreCreateBinary();

    ipc.lock = xSemaphoreCreateMutex();
    xSemaphoreGive(ipc.lock);
}
//-----------------------------------------------------------------------------
int32_t ipc_client_zynq_irq_send(void){

    /* Makes sure semaphore is taken */
    xSemaphoreTake(ipc.cpu1_semaphore, 0);

    /* Generates a software interrupt on CPU1 */
    XScuGic_SoftwareIntr(
        ipc.intc_instance,
        IPC_CLIENT_ZYNQ_INT_CPU0_TO_CPU1,
        IPC_CLIENT_ZYNQ_CONFIG_SIG_CPU1_ID
    );

    return 0;
}
//-----------------------------------------------------------------------------
int32_t ipc_client_zynq_irq_receive(uint32_t timeout){

    /* Waits until CPU1 replies back */
    if( xSemaphoreTake(ipc.cpu1_semaphore, timeout/portTICK_PERIOD_MS) != pdTRUE ){
        return IPC_CLIENT_ZYNQ_ERR_CPU1_REPLY_TO;
    }

    return 0;
}
//-----------------------------------------------------------------------------
int32_t ipc_client_zynq_lock(uint32_t timeout){

    if( xSemaphoreTake(ipc.lock, timeout/portTICK_PERIOD_MS) != pdTRUE ){
        return IPC_CLIENT_ZYNQ_ERR_LOCK_TO;
    }

    return 0;
}
//-----------------------------------------------------------------------------
void ipc_client_zynq_unlock(void){

    xSemaphoreGive(ipc.lock);
}
//-----------------------------------------------------------------------------
//=============================================================================

//=============================================================================
/*----------------------------------- IRQ -----------------------------------*/
//=============================================================================
//-----------------------------------------------------------------------------
void ipc_client_zynq_irq(void *callback_ref){

    (void) callback_ref;

    BaseType_t xHigherPriorityTaskWoken;

    xSemaphoreGiveFromISR( ipc.cpu1_semaphore, &xHigherPriorityTaskWoken );

    portYIELD_FROM_ISR( xHigherPriorityTaskWoken );
}
//-----------------------------------------------------------------------------
//=============================================================================
